### ISSUE TITLE
lack redirect_params on media answer request body

### ISSUE THREAD

**Issue by atotto** [skyway/skyway-webrtc-gateway#10]
http://35.200.46.204/#/3.media/media_connection_answer にて、`redirect_params` が欠けているようです。

https://github.com/skyway/skyway-webrtc-gateway/blob/ff1b09bf7b3a2aa4cd22a820ef728bae5821bbdb/api/api.yaml#L1569
https://github.com/skyway/skyway-webrtc-gateway/blob/1c65fca8b8ce75aac75e85f605117539777ed809/samples/util.rb#L150

お手数ですが確認をお願いいたします。

**Comment by nakakura** [comment]
ご連絡頂きありがとうございます！
修正致しましたのでご確認いただけますでしょうか。

**Comment by atotto** [comment]
対応ありがとうございます！良さそうです。
今後ともよろしくお願いします。

**Comment by nakakura** [comment]
ありがとうございました！
