### ISSUE TITLE
I can't watch live stream

### ISSUE THREAD

**Issue by leomaring** [skyway/skyway-webrtc-gateway#18]
@nakakura 
I run your example:
**ruby media_callee.rb:**
`
you can send video RTP packet to at 172.24.0.2:50011 as vi-b8de61ca-c39f-4b8b-9169-fe71cf11357a
you can send video RTCP packet to at 172.24.0.2:50013 as rc-a040948a-4ec8-4b53-a08d-c0f0b254d707
you can send audio RTP packet to at 172.24.0.2:50012 as au-fc6777a6-9956-4263-898f-3d82bbdf0929
you can send audio RTCP packet to at 172.24.0.2:50014 as rc-a040948a-4ec8-4b53-a08d-c0f0b254d707
video from media_caller2 will redirect to  127.0.0.1:20000
video RTCP from media_caller2 will redirect to  127.0.0.1:20010
audio from media_caller2 will redirect to  127.0.0.1:20001
audio RTCP from media_caller2 will redirect to  127.0.0.1:20011
`

**ruby media_caller.rb** 
`
you can send video RTP packet to at 172.24.0.2:50015 as vi-8d6cdf2e-2417-4ca9-8487-57ade3d178aa
you can send video RTCP packet to at 172.24.0.2:50017 as rc-8111b2ff-30e0-4f4f-8e76-69665552aa0e
you can send audio RTP packet to at 172.24.0.2:50016 as au-f7df2909-ab18-4bc0-bf28-d929bc0b57eb
you can send audio RTCP packet to at 172.24.0.2:50018 as rc-ccb7d3c8-b259-40f0-8ad0-929a9da9bfec
video from media_callee2 will redirect to  127.0.0.1:20000
video RTCP from media_callee2 will redirect to  127.0.0.1:20010
audio from media_callee2 will redirect to  127.0.0.1:20001
audio RTCP from media_callee2 will redirect to  127.0.0.1:20011
` 

Then I tried to test by using VLC Player to start stream:
![start-stream](https://user-images.githubusercontent.com/44110129/68015470-d04ce280-fcc4-11e9-9eb1-a62cef310fe6.png)

The i try to view live stream from rtp://127.0.0.1:20000,
But it's empty. Please tell me know what's my wrong

**Comment by nakakura** [comment]
The application seems to be for Mac, so I guess you executed WebRTC Gateway in another machine.
WebRTC Gateway redirect the stream to 127.0.0.1(localhost), so it is natural that the stream is not sent to Mac.

**Comment by nakakura** [comment]
According to the information, WebRTC Gateway seems to work correctly.
Also, no response from  @leomaring, so I'll close this issue.
If you still have problems, you can re-open it.
