### ISSUE TITLE
DataChannelにてデータ送受信が正常に行われない

### ISSUE THREAD

**Issue by hiroyuki-cv** [skyway/skyway-webrtc-gateway#32]
MediaChannelは正常にGateway経由でChromeに送信し再生できているのですが、
DataChannelでデータを送受信しようとすると正常に通信できない事象が発生しております。

挙動は以下画像の通り、
・aeiouをGateway経由でChromeに送信した場合、97がChrome側で受信され、送信した文字列と全く合っていない
・Chromeからtestと送信した場合、文字列testの前に何らかのバイト列が挿入されUDPで送信される
です。

![image923](https://user-images.githubusercontent.com/17847727/117549591-3b276880-b076-11eb-846a-46fa7da8eba3.png)

また、環境は以下の通りです。
・gateway／ブラウザ共にFedora 32 (x86_64)環境で実行
・ブラウザはChrome 90.0.4430.93（Official Build） （64 ビット）
・gateway_linux_x64（v0.3.2）を使用
・御社[P2P Dataデモサイト](https://example.webrtc.ecl.ntt.com/p2p-data/index.html)のAPIキー(5bea...c480)を指定し、data_callee.rbを実行した後、Chromeにて御社P2P Dataデモサイトで挙動を確認しました
　→P2P Data exampleを自前のサーバーにダウンロードし、新規発行したAPIキーで行っても同様の挙動でした

Gateway経由のDataChannelにつきまして制約等ございますでしょうか？

**Comment by ibuibu** [comment]
SkyWayサポートに頂いた同様の内容の投稿に回答をさせていただきましたので、本issueはクローズとさせていただきます。
